// Generated by tokens-dtcg. Do not edit.
package designtokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ColorWhite = Color(0xFFFFFFFF)
    val ColorBlack = Color(0xFF0A0A0A)
    val ColorSlate50 = Color(0xFFF8FAFC)
    val ColorSlate100 = Color(0xFFF1F5F9)
    val ColorSlate200 = Color(0xFFE2E8F0)
    val ColorSlate300 = Color(0xFFCBD5E1)
    val ColorSlate400 = Color(0xFF94A3B8)
    val ColorSlate500 = Color(0xFF64748B)
    val ColorSlate600 = Color(0xFF475569)
    val ColorSlate700 = Color(0xFF334155)
    val ColorSlate800 = Color(0xFF1E293B)
    val ColorSlate900 = Color(0xFF0F172A)
    val ColorBlue50 = Color(0xFFEFF6FF)
    val ColorBlue100 = Color(0xFFDBEAFE)
    val ColorBlue500 = Color(0xFF3B82F6)
    val ColorBlue600 = Color(0xFF2563EB)
    val ColorBlue700 = Color(0xFF1D4ED8)
    val ColorGreen50 = Color(0xFFF0FDF4)
    val ColorGreen500 = Color(0xFF22C55E)
    val ColorGreen600 = Color(0xFF16A34A)
    val ColorAmber50 = Color(0xFFFFFBEB)
    val ColorAmber500 = Color(0xFFF59E0B)
    val ColorAmber600 = Color(0xFFD97706)
    val ColorRed50 = Color(0xFFFEF2F2)
    val ColorRed500 = Color(0xFFEF4444)
    val ColorRed600 = Color(0xFFDC2626)
    val Space0 = 0.dp
    val Space1 = 4.dp
    val Space2 = 8.dp
    val Space3 = 12.dp
    val Space4 = 16.dp
    val Space5 = 20.dp
    val Space6 = 24.dp
    val Space8 = 32.dp
    val Space10 = 40.dp
    val Space12 = 48.dp
    val RadiusNone = 0.dp
    val RadiusSm = 4.dp
    val RadiusMd = 8.dp
    val RadiusLg = 12.dp
    val RadiusFull = 9999.dp
    val FontSizeSm = 14.dp
    val FontSizeMd = 16.dp
    val FontSizeLg = 20.dp
    val FontSizeXl = 24.dp
    val ColorBgDefault = Color(0xFF[OBJECT OBJECT])
    val ColorBgSubtle = Color(0xFF[OBJECT OBJECT])
    val ColorBgMuted = Color(0xFF[OBJECT OBJECT])
    val ColorFgDefault = Color(0xFF[OBJECT OBJECT])
    val ColorFgMuted = Color(0xFF[OBJECT OBJECT])
    val ColorFgOnAccent = Color(0xFF[OBJECT OBJECT])
    val ColorBorderDefault = Color(0xFF[OBJECT OBJECT])
    val ColorBorderStrong = Color(0xFF[OBJECT OBJECT])
    val ColorAccentDefault = Color(0xFF[OBJECT OBJECT])
    val ColorAccentHover = Color(0xFF[OBJECT OBJECT])
    val ColorAccentSubtle = Color(0xFF[OBJECT OBJECT])
    val ColorSuccessFg = Color(0xFF[OBJECT OBJECT])
    val ColorSuccessBg = Color(0xFF[OBJECT OBJECT])
    val ColorWarningFg = Color(0xFF[OBJECT OBJECT])
    val ColorWarningBg = Color(0xFF[OBJECT OBJECT])
    val ColorDangerFg = Color(0xFF[OBJECT OBJECT])
    val ColorDangerBg = Color(0xFF[OBJECT OBJECT])
    val ColorInfoFg = Color(0xFF[OBJECT OBJECT])
    val ColorInfoBg = Color(0xFF[OBJECT OBJECT])
    val SpaceInsetSm = 0.dp
    val SpaceInsetMd = 0.dp
    val SpaceInsetLg = 0.dp
    val SpaceStackSm = 0.dp
    val SpaceStackMd = 0.dp
    val RadiusControl = 0.dp
    val RadiusSurface = 0.dp
    const val IconCheckIcon = "Check"
    const val IconCloseIcon = "Close"
    const val IconInfoIcon = "Info"
    const val IconWarningIcon = "Warning"
    const val IconErrorIcon = "Error"
    const val IconSuccessIcon = "CheckCircle"
    const val IconStarIcon = "Star"
    const val IconHeartIcon = "Favorite"
    const val IconChevronIcon = "ChevronRight"
}
