/** Generated by tokens-dtcg. Do not edit. */
export default {
  "colors": {
    "white": "var(--color-white)",
    "black": "var(--color-black)",
    "slate": {
      "50": "var(--color-slate-50)",
      "100": "var(--color-slate-100)",
      "200": "var(--color-slate-200)",
      "300": "var(--color-slate-300)",
      "400": "var(--color-slate-400)",
      "500": "var(--color-slate-500)",
      "600": "var(--color-slate-600)",
      "700": "var(--color-slate-700)",
      "800": "var(--color-slate-800)",
      "900": "var(--color-slate-900)"
    },
    "blue": {
      "50": "var(--color-blue-50)",
      "100": "var(--color-blue-100)",
      "500": "var(--color-blue-500)",
      "600": "var(--color-blue-600)",
      "700": "var(--color-blue-700)"
    },
    "green": {
      "50": "var(--color-green-50)",
      "500": "var(--color-green-500)",
      "600": "var(--color-green-600)"
    },
    "amber": {
      "50": "var(--color-amber-50)",
      "500": "var(--color-amber-500)",
      "600": "var(--color-amber-600)"
    },
    "red": {
      "50": "var(--color-red-50)",
      "500": "var(--color-red-500)",
      "600": "var(--color-red-600)"
    },
    "bg": {
      "default": "var(--color-bg-default)",
      "subtle": "var(--color-bg-subtle)",
      "muted": "var(--color-bg-muted)"
    },
    "fg": {
      "default": "var(--color-fg-default)",
      "muted": "var(--color-fg-muted)",
      "onAccent": "var(--color-fg-onAccent)"
    },
    "border": {
      "default": "var(--color-border-default)",
      "strong": "var(--color-border-strong)"
    },
    "accent": {
      "default": "var(--color-accent-default)",
      "hover": "var(--color-accent-hover)",
      "subtle": "var(--color-accent-subtle)"
    },
    "success": {
      "fg": "var(--color-success-fg)",
      "bg": "var(--color-success-bg)"
    },
    "warning": {
      "fg": "var(--color-warning-fg)",
      "bg": "var(--color-warning-bg)"
    },
    "danger": {
      "fg": "var(--color-danger-fg)",
      "bg": "var(--color-danger-bg)"
    },
    "info": {
      "fg": "var(--color-info-fg)",
      "bg": "var(--color-info-bg)"
    }
  },
  "spacing": {
    "0": "var(--space-0)",
    "1": "var(--space-1)",
    "2": "var(--space-2)",
    "3": "var(--space-3)",
    "4": "var(--space-4)",
    "5": "var(--space-5)",
    "6": "var(--space-6)",
    "8": "var(--space-8)",
    "10": "var(--space-10)",
    "12": "var(--space-12)",
    "inset-sm": "var(--space-inset-sm)",
    "inset-md": "var(--space-inset-md)",
    "inset-lg": "var(--space-inset-lg)",
    "stack-sm": "var(--space-stack-sm)",
    "stack-md": "var(--space-stack-md)"
  },
  "borderRadius": {
    "none": "var(--radius-none)",
    "sm": "var(--radius-sm)",
    "md": "var(--radius-md)",
    "lg": "var(--radius-lg)",
    "full": "var(--radius-full)",
    "control": "var(--radius-control)",
    "surface": "var(--radius-surface)"
  },
  "fontSize": {
    "sm": "var(--font-size-sm)",
    "md": "var(--font-size-md)",
    "lg": "var(--font-size-lg)",
    "xl": "var(--font-size-xl)"
  }
};
