/** Generated by tokens-dtcg. Do not edit. */
export const tokens = {
  "color": {
    "white": "#ffffff",
    "black": "#0a0a0a",
    "slate": {
      "50": "#f8fafc",
      "100": "#f1f5f9",
      "200": "#e2e8f0",
      "300": "#cbd5e1",
      "400": "#94a3b8",
      "500": "#64748b",
      "600": "#475569",
      "700": "#334155",
      "800": "#1e293b",
      "900": "#0f172a"
    },
    "blue": {
      "50": "#eff6ff",
      "100": "#dbeafe",
      "500": "#3b82f6",
      "600": "#2563eb",
      "700": "#1d4ed8"
    },
    "green": {
      "50": "#f0fdf4",
      "500": "#22c55e",
      "600": "#16a34a"
    },
    "amber": {
      "50": "#fffbeb",
      "500": "#f59e0b",
      "600": "#d97706"
    },
    "red": {
      "50": "#fef2f2",
      "500": "#ef4444",
      "600": "#dc2626"
    },
    "bg": {
      "default": {
        "value": "#ffffff",
        "type": "color",
        "ext": null
      },
      "subtle": {
        "value": "#f8fafc",
        "type": "color",
        "ext": null
      },
      "muted": {
        "value": "#f1f5f9",
        "type": "color",
        "ext": null
      }
    },
    "fg": {
      "default": {
        "value": "#0f172a",
        "type": "color",
        "ext": null
      },
      "muted": {
        "value": "#64748b",
        "type": "color",
        "ext": null
      },
      "onAccent": {
        "value": "#ffffff",
        "type": "color",
        "ext": null
      }
    },
    "border": {
      "default": {
        "value": "#e2e8f0",
        "type": "color",
        "ext": null
      },
      "strong": {
        "value": "#cbd5e1",
        "type": "color",
        "ext": null
      }
    },
    "accent": {
      "default": {
        "value": "#2563eb",
        "type": "color",
        "ext": null
      },
      "hover": {
        "value": "#1d4ed8",
        "type": "color",
        "ext": null
      },
      "subtle": {
        "value": "#eff6ff",
        "type": "color",
        "ext": null
      }
    },
    "success": {
      "fg": {
        "value": "#16a34a",
        "type": "color",
        "ext": null
      },
      "bg": {
        "value": "#f0fdf4",
        "type": "color",
        "ext": null
      }
    },
    "warning": {
      "fg": {
        "value": "#d97706",
        "type": "color",
        "ext": null
      },
      "bg": {
        "value": "#fffbeb",
        "type": "color",
        "ext": null
      }
    },
    "danger": {
      "fg": {
        "value": "#dc2626",
        "type": "color",
        "ext": null
      },
      "bg": {
        "value": "#fef2f2",
        "type": "color",
        "ext": null
      }
    },
    "info": {
      "fg": {
        "value": "#2563eb",
        "type": "color",
        "ext": null
      },
      "bg": {
        "value": "#eff6ff",
        "type": "color",
        "ext": null
      }
    }
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "inset": {
      "sm": 0,
      "md": 0,
      "lg": 0
    },
    "stack": {
      "sm": 0,
      "md": 0
    }
  },
  "radius": {
    "none": 0,
    "sm": 4,
    "md": 8,
    "lg": 12,
    "full": 9999,
    "control": 0,
    "surface": 0
  },
  "font": {
    "family": {
      "sans": "Inter, system-ui, sans-serif"
    },
    "size": {
      "sm": 14,
      "md": 16,
      "lg": 20,
      "xl": 24
    },
    "weight": {
      "regular": 400,
      "medium": 500,
      "bold": 700
    }
  }
} as const;
