#!/usr/bin/env node
/**
 * tokens-dtcg build
 * -----------------
 * Reads DTCG token sources (core -> semantic -> icons), resolves {alias}
 * references into a flat registry, then emits platform outputs:
 *   - registry.json        canonical resolved registry (source of truth for guards)
 *   - tokens.css           CSS custom properties
 *   - tailwind-theme.js    Tailwind theme.extend fragment
 *   - tokens.d.ts          TypeScript token-name union + typed accessor
 *   - DesignTokens.swift   Swift enum/extension
 *   - DesignTokens.kt      Kotlin object of vals
 *   - tokens-rn.ts         React Native JS token object
 *
 * No external dependencies: pure Node.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../../..');
const SRC = resolve(ROOT, '_shared/tokens/source');
const OUT = resolve(ROOT, '_shared/tokens');

const SOURCES = ['core.tokens.json', 'semantic.tokens.json', 'icons.tokens.json'];

/** Walk a DTCG tree, collecting leaf tokens keyed by dot-path. */
function flatten(node, path, type, acc) {
  const nodeType = node.$type ?? type;
  if (node && typeof node === 'object' && '$value' in node) {
    acc[path] = {
      value: node.$value,
      type: node.$type ?? type,
      ext: node.$extensions ?? null,
    };
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (child && typeof child === 'object') {
      flatten(child, path ? `${path}.${key}` : key, nodeType, acc);
    }
  }
}

/** Resolve {a.b.c} alias chains to concrete values. */
function resolveAliases(raw) {
  const resolved = {};
  const seen = new Set();
  const resolveOne = (name, stack = []) => {
    if (name in resolved) return resolved[name];
    if (stack.includes(name)) {
      throw new Error(`Circular token reference: ${[...stack, name].join(' -> ')}`);
    }
    const token = raw[name];
    if (!token) throw new Error(`Unknown token referenced: {${name}}`);
    let value = token.value;
    if (typeof value === 'string') {
      const m = value.match(/^\{([^}]+)\}$/);
      if (m) value = resolveOne(m[1], [...stack, name]);
    }
    resolved[name] = { ...token, value };
    seen.add(name);
    return value;
  };
  for (const name of Object.keys(raw)) resolveOne(name);
  return resolved;
}

function loadAll() {
  const raw = {};
  for (const file of SOURCES) {
    const json = JSON.parse(readFileSync(resolve(SRC, file), 'utf8'));
    flatten(json, '', undefined, raw);
  }
  return resolveAliases(raw);
}

const cssVar = (name) => `--${name.replace(/\./g, '-')}`;
const isColor = (t) => t.type === 'color';
const isDimension = (t) => t.type === 'dimension';

function emitCss(reg) {
  const lines = [':root {'];
  for (const [name, t] of Object.entries(reg)) {
    if (t.type === 'icon') continue;
    lines.push(`  ${cssVar(name)}: ${t.value};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function emitTailwind(reg) {
  const colors = {}, spacing = {}, radius = {}, fontSize = {};
  const setPath = (obj, path, val) => {
    const parts = path.split('.');
    let cur = obj;
    for (let i = 0; i < parts.length - 1; i++) cur = (cur[parts[i]] ??= {});
    cur[parts[parts.length - 1]] = val;
  };
  for (const [name, t] of Object.entries(reg)) {
    if (name.startsWith('color.')) setPath(colors, name.slice(6), `var(${cssVar(name)})`);
    else if (name.startsWith('space.')) spacing[name.slice(6).replace(/\./g, '-')] = `var(${cssVar(name)})`;
    else if (name.startsWith('radius.')) radius[name.slice(7).replace(/\./g, '-')] = `var(${cssVar(name)})`;
    else if (name.startsWith('font.size.')) fontSize[name.slice(10)] = `var(${cssVar(name)})`;
  }
  const theme = { colors, spacing, borderRadius: radius, fontSize };
  return `/** Generated by tokens-dtcg. Do not edit. */\nexport default ${JSON.stringify(theme, null, 2)};\n`;
}

function emitDts(reg) {
  const names = Object.keys(reg).filter((n) => reg[n].type !== 'icon');
  const union = names.map((n) => `  | '${n}'`).join('\n');
  return `/** Generated by tokens-dtcg. Do not edit. */\nexport type TokenName =\n${union};\n\n`
    + `export const tokens: Record<TokenName, string> = {\n`
    + names.map((n) => `  '${n}': 'var(${cssVar(n)})',`).join('\n')
    + `\n};\n\nexport const token = (name: TokenName): string => tokens[name];\n`;
}

const pascal = (s) => s.replace(/(^|[.\-_])([a-z0-9])/g, (_, __, c) => c.toUpperCase());

function emitSwift(reg) {
  const lines = [
    '// Generated by tokens-dtcg. Do not edit.',
    'import SwiftUI',
    '',
    'public enum DesignTokens {',
  ];
  for (const [name, t] of Object.entries(reg)) {
    if (t.type === 'icon') {
      lines.push(`    public static let ${pascal(name.replace('icon.', 'icon.'))}Symbol = "${t.ext?.sfSymbol ?? t.value}"`);
    } else if (isColor(t)) {
      const hex = String(t.value).replace('#', '');
      lines.push(`    public static let ${pascal(name)} = Color(hex: "${hex}")`);
    } else if (isDimension(t)) {
      const px = parseFloat(String(t.value)) || 0;
      lines.push(`    public static let ${pascal(name)}: CGFloat = ${px}`);
    }
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function emitKotlin(reg) {
  const lines = [
    '// Generated by tokens-dtcg. Do not edit.',
    'package designtokens',
    '',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.compose.ui.unit.dp',
    '',
    'object DesignTokens {',
  ];
  for (const [name, t] of Object.entries(reg)) {
    const id = pascal(name);
    if (t.type === 'icon') {
      lines.push(`    const val ${id}Icon = "${t.ext?.material ?? t.value}"`);
    } else if (isColor(t)) {
      const hex = String(t.value).replace('#', '').toUpperCase();
      lines.push(`    val ${id} = Color(0xFF${hex})`);
    } else if (isDimension(t)) {
      const px = parseFloat(String(t.value)) || 0;
      lines.push(`    val ${id} = ${px}.dp`);
    }
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function emitRn(reg) {
  const obj = {};
  const setPath = (path, val) => {
    const parts = path.split('.');
    let cur = obj;
    for (let i = 0; i < parts.length - 1; i++) cur = (cur[parts[i]] ??= {});
    cur[parts[parts.length - 1]] = val;
  };
  for (const [name, t] of Object.entries(reg)) {
    if (t.type === 'icon') continue;
    const val = isDimension(t) ? (parseFloat(String(t.value)) || 0) : t.value;
    setPath(name, val);
  }
  return `/** Generated by tokens-dtcg. Do not edit. */\nexport const tokens = ${JSON.stringify(obj, null, 2)} as const;\n`;
}

function main() {
  const reg = loadAll();
  mkdirSync(OUT, { recursive: true });

  const registryOut = {};
  for (const [name, t] of Object.entries(reg)) {
    registryOut[name] = { value: t.value, type: t.type, ...(t.ext ? { extensions: t.ext } : {}) };
  }

  const files = {
    'registry.json': JSON.stringify(registryOut, null, 2) + '\n',
    'tokens.css': emitCss(reg),
    'tailwind-theme.js': emitTailwind(reg),
    'tokens.d.ts': emitDts(reg),
    'DesignTokens.swift': emitSwift(reg),
    'DesignTokens.kt': emitKotlin(reg),
    'tokens-rn.ts': emitRn(reg),
  };

  for (const [file, content] of Object.entries(files)) {
    writeFileSync(resolve(OUT, file), content);
  }

  const count = Object.keys(reg).length;
  console.log(`tokens-dtcg: resolved ${count} tokens -> ${Object.keys(files).length} platform outputs`);
  for (const file of Object.keys(files)) console.log(`  _shared/tokens/${file}`);
}

main();
